Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,6 +32,9 @@ jobs:
           pwd
           echo "Contents of the dbt directory:"
           ls -la dbt
+          
+      - name: Create log directory
+        run: mkdir -p ./custom_logs
  
       - name: Run dbt commands
         env:
@@ -39,9 +42,17 @@ jobs:
             POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
             POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
         run: |
-            dbt debug --profiles-dir ./dbt --project-dir ./dbt --log-level debug --log-format json
-            dbt deps --profiles-dir ./dbt --project-dir ./dbt
-            dbt run --profiles-dir ./dbt --project-dir ./dbt --target dev
+          dbt debug --profiles-dir ./dbt --project-dir ./dbt --log-level debug --log-format json --log-path ./custom_logs/ || true
+          dbt deps --profiles-dir ./dbt --project-dir ./dbt --log-level debug --log-format json --log-path ./custom_logs/
+          dbt run --profiles-dir ./dbt --project-dir ./dbt --target dev --log-level debug --log-format json --log-path ./custom_logs/
+
+      - name: Check dbt logs
+        run: |
+          echo "=== Fichiers de logs générés ==="
+          ls -la ./custom_logs/
+          echo "=== Dernières erreurs ==="
+          cat ./custom_logs/dbt.log | jq -c '. | select(.levelname == "ERROR")' || echo "Aucune erreur trouvée"
+          
       - name: Perform Soda Scan
         uses: sodadata/soda-github-action@main
         continue-on-error: true
